config/routes.rb
Rails.application.routes.draw do
  concern  :votable do
    member do #Create actually calls the CRUD method which figures out whether to Create, Update or Destroy the vote.
      get 'vote_up'
      get 'vote_down'
    end
  end
  
  concern :commentable do
    resources :comments, only: [:create, :index] do
      collection do
        get 'get_all'
      end
    end
  end
  
  resources :discussions, only: [:new, :create] do #Allowed creating new items only from logged user
  end
  
  resources :comments, concerns: [:votable, :commentable]
  
  resources :users do
    collection do
      get 'by_email'
    end
    resources :positions, only: [:index] do
    end
    resources :discussions, except: [:new, :create], shallow: true, concerns: [:votable, :commentable] do 
      member do
        get 'publish'
      end
      resources :positions, shallow: true, concerns: [:votable, :commentable] do
        collection do
          post 'new_token'
        end
      end
    end
  end
  
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  
  get 'signup' => 'users#new'
  
  delete 'logout' => 'sessions#destroy'
  
  get 'auth/:provider', to: redirect('/auth/%{provider}'), as: :social_login
  get 'auth/:provider/callback', to: 'sessions#oauthcreate'
  get 'auth/failure', to: redirect('/')
  
  get 'home' => 'home#stories'

  root 'sessions#redirect'

end

app/models/discussion.rb
class Discussion < ActiveRecord::Base
  include Votable
  include Commentable
  
  belongs_to :user
  belongs_to :topic
  belongs_to :type, class_name:"DiscussionType", foreign_key:"discussion_type_id"
  has_many :positions
  has_many :active_positions, ->{active}, class_name:"Position"

  validates :header, presence: true, length:{minimum:5,maximum:50}
  validates :user, presence: true
  validates :topic, presence: true
  validates :type, presence: true
  validates :published, absence: { message: " Problem: Discussion is already published" }
  default_scope {(order(created_at: :desc))}
  scope :published, ->{where(published: true)}
  scope :unpublished, ->{where(published: nil)}
  def editable?(user)
    user.owns?(self)&&editable_conditions?
  end

  #Just in case
  def publish_without_saving
    update_attribute(:published,true)
  end

  def publish!
    save
    update_attribute(:published,true)
  end

  private

  def editable_conditions?
    !id.nil? && !published
  end
end

app/models/discussion_type.rb
class DiscussionType < ActiveRecord::Base
  
end

app/controllers/discussions_controller.rb
class DiscussionsController < ApplicationController
  include VotableController
  before_action :set_discussion, only: [:show, :edit, :update, :destroy, :publish]
  before_action :get_user_or_redirect
  before_action only: [:edit, :destroy, :update] do
    match_user(@discussion)
  end

  # GET /discussions
  # GET /discussions.json
  def index
    @from_user = User.find(params[:user_id])
    @published = @from_user.discussions.published
    if @user.owns? @from_user
      @unpublished = @from_user.discussions.unpublished
    end
  end

  # GET /discussions/1
  # GET /discussions/1.json
  def show
    @positions = @discussion.positions.includes(:user,:comments)
  end

  def publish
    @discussion.publish!
    redirect_to discussion_path(@discussion), flash:{notice: "Published!"}
  end

  # GET /discussions/new
  def new
    @discussion = Discussion.new
  end

  # GET /discussions/1/edit
  def edit
  end

  # POST /discussions
  # POST /discussions.json
  def create
    @discussion = Discussion.new(discussion_params)
    @discussion.user = @user
    respond_to do |format|
      if @discussion.save
        format.html { redirect_to @discussion, notice: 'Discussion was successfully created.' }
        format.json { render :show, status: :created, location: @discussion }
      else
        format.html { render :new }
        format.json { render json: @discussion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /discussions/1
  # PATCH/PUT /discussions/1.json
  def update
    respond_to do |format|
      if @discussion.update(discussion_params)
        format.html { redirect_to @discussion, notice: 'Discussion was successfully updated.' }
        format.json { render :show, status: :ok, location: @discussion }
      else
        format.html { render :edit }
        format.json { render json: @discussion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /discussions/1
  # DELETE /discussions/1.json
  def destroy
    @discussion.destroy
    respond_to do |format|
      format.html { redirect_to discussions_url, notice: 'Discussion was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_discussion
    @discussion = Discussion.find(params[:id])
  end

  def set_votable
    set_discussion
    @votable=@discussion
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def discussion_params
    params.require(:discussion).permit(:header, :body, :discussion_type_id, :topic_id)
  end
end

app/helpers/discussions_helper.rb
module DiscussionsHelper
end

app/views/discussions/_body.html.erb
<div class="caption body">
  <div class="well center">
      <%= simple_format(discussion.body, style: "text-align: left;") %>
  </div>
  <div class="social center">
    <%= social_share_button_tag(discussion.header, popup: "true", url: polymorphic_url(discussion)) %>
  </div>
</div>

app/views/discussions/_content.html.erb
<%= render partial: 'discussions/header', locals: {discussion: discussion} %>
<%= render partial: 'discussions/body', locals: {discussion: discussion} %>

app/views/discussions/_discussion.html.erb
<% see_discussion ||= "See all..." %>
<div class="col-sm-12 col-md-12">
<div class="thumbnail article">
    <%= render partial: 'discussions/content', locals: {discussion: discussion} %>
    <div class="caption footer">
      <h3 class="center">
        Positions:
        <%= badge span(discussion.active_positions.first(2).count)+span("/")+span(discussion.active_positions.count) %>
        <%= link_to see_discussion, discussion, class: "btn btn-default btn-xs" %>
      </h3>
      <div class="container-fluid center">
        <% discussion.active_positions.first(2).each_slice(2) do |row| %>
            <div class="row">
              <%= render partial: row, locals: {no_comments: true}%>
            </div>
        <% end %>
      </div>
    </div>

  <%= render(partial: 'edit_options', locals: {discussion: discussion}) if owns? discussion unless discussion.published? %>
  </div>

</div>

app/views/discussions/_edit_options.html.erb
<hr>
<%=link_to "Edit your discussion", discussion, class: "btn btn-primary btn-xl" %>
<%= render partial: "publish", locals: {discussion: discussion}%>

app/views/discussions/_form.html.erb
<%= form_for(@discussion, class:"form-publish") do |f| %> <h1><%= @config[:h1]%></h1>
<div class="field">
	<%= f.label :header %>
	<br>
	<%= f.text_field :header,  class:"form-control" %>
</div>
<div class="field">
	<%= f.label :body %>
	<br>
	<%= f.text_area :body,  class:"form-control"%>
</div>
<div class="field">
	<%= f.label :discussion_type_id %>
	<br>
	<%= f.select :discussion_type_id, DiscussionType.all.collect {|x| [x.name, x.id]}, class:"form-control" %>
</div>
<div class="field">
	<%= f.label :topic_id %>
	<br>
	<%= f.select :topic_id, Topic.all.collect {|x| [x.name, x.id]}, class:"form-control" %>
</div>
<div class="actions">
	<%= f.submit class:"btn btn-primary" %>
</div>
<% end %>

app/views/discussions/_generate_token.html.erb
<div class="row">
	<div class="col-sm-4 col-md-4" id="search-box">
		<div class="thumbnail">
			<h3 class="center">
				Or invite anyone with an invite link</h3>
			<div class="caption">
        <% link_design = span(span("", class: "glyphicon glyphicon-share-alt")+span(" Generate Link"), class:"btn btn-default form-control") %>
        <%= link_to link_design, new_token_discussion_positions_path(@discussion) , remote: true, method: :post, format: :json%>

			</div>
		</div>
	</div>
	<div class="col-sm-8 col-md-8" id="link-box">
		<div class="thumbnail">
			<div class="caption">
				<p>Copy using Ctrl (Or Cmd) + C or right click and copy the link and share.</p>
        <p><b>Remember!</b> Only 1 person per link!</p>
        <input type="url" id="link-box-link" placeholder="Invitation link" class="form-control">

		  </div>
	  </div>
  </div>
</div>

app/views/discussions/_header.html.erb
<div class="top-left">
  <%= votable_tag discussion, style: :arrows %>
</div>
<div class="caption header">

  <h2>
    <div class="center">
      <div class="spacer"></div> <%= span discussion.header %> </div>
  </h2>
  <div class="center">
    <p>
      By <%= link_to_user(discussion.user) %>
      <%= link_to '| Edit', edit_discussion_path(discussion) if owns?(discussion) %>
    </p>
    <ul>
      <li>
        <%= discussion.type.name %>
      </li>
      <li>
        <%= discussion.topic.name %>
      </li>
    </ul>
  </div>
</div>

app/views/discussions/_look_for_user.html.erb
<h2>Invite people to the discussion:</h2>
<div class="well">
	<h4>Add everyone to this argument so they can express their opinion/position.</h4>
</div>

<% @config[:look_for_user]={} %>
<% @config[:look_for_user][:invite_link]=new_discussion_position_path(@discussion) %>

<div class="row">
	<div class="col-sm-4 col-md-4" id="search-box">
		<div class="thumbnail">
			<h3 class="center">
				Look for user</h3>
			<div class="caption">
				<%= form_for(:user, url: by_email_users_path, remote: true, format: :json, method: :get, html: {id: "search_form", data:{type:'json'}}) do |f| %>
				<%= f.email_field :email, placeholder: "E-mail", class: "form-control" %>
				<br>
				<%= button_tag content_tag(:span, " Search", class: "glyphicon glyphicon-search"), class: "form-control" %>
				<% end %>
			</div>
		</div>
	</div>
	<div class="col-sm-8 col-md-8" id="user-box">
		<div class="thumbnail">
			<h3>User found!</h3>
			<div class="caption">
				<p>
					<b id="user_result_full_name"></b> was found using email <b id="user_result_email"></b>
				</p>
				<script>var route = "<%= @config[:look_for_user][:invite_link]%>";</script>
				<center>
					<%= link_to 'Invite Him', "#", id: "invite_link", class: "btn btn-primary invite_link" %>
				</center>
			</div>
		</div>
	</div>
	<div class="col-sm-8 col-md-8" id="invite-box">
		<div class="thumbnail">
			<h3>
			<center>
				No user was found
			</center></h3>
			<div class="caption">
				<p>
					No user was found with e-mail: <b data-param="email"></b>
				</p>
				<center>
					<%= link_to 'Invite Him', "#", id: "invite_link_2", class: "btn btn-primary invite_link", "data-param" => "email" %>
				</center>
			</div>
		</div>
	</div>
</div>

app/views/discussions/_publish.html.erb
<hr>
<h3><%=span "", class:"glyphicon glyphicon-warning-sign"%> <%=span "Remember!"%></h3>
<b>Remember before publishing that no modifications can be made to the discussion or the positions afterwards</b>
<br>
<br>
<%= link_to "PUBLISH", publish_discussion_path(discussion), class:"btn btn-success center"%>

app/views/discussions/edit.html.erb
<%= render 'form' %>

<%= link_to 'Show', @discussion %>

app/views/discussions/index.html.erb
<!-- TODO DRY THIS AS ITS SIMILAR TO HOME -->
<div class="page-header">
	<h1><%= @from_user.full_name %> Discussions:</h1>
</div>
<div class="body">
	<% if owns? @from_user %>

	<h3> Unpublished: </h3>
	<% @unpublished.each_slice(3).each do |row| %>
	<div class="row">
		<%= render row %>
	</div>
	<hr />
	<h3> Published: </h3>
	<% end %>
	<% end %>
	<% @published.each_slice(3).each do |row| %>
	<div class="row">
		<%= render row %>
	</div>
	<% end %>

</div>

app/views/discussions/new.html.erb
<%= render 'form' %>

app/views/discussions/show.html.erb
<div class="article">

  <%= render partial: 'discussions/content', locals: {discussion: @discussion} %>

	<div class="content">
		<h3 class="center">
			Positions:
		</h3>
		<div class="container-fluid">
			<%@positions.each_slice(2) do |row|%>
			<div class="row">
				<%= render row%>
			</div>
			<%end%>

		</div>
    <hr>

    <%= commentable_tag @discussion if @discussion.published?%>
	</div>
	<%if editable? @discussion%>
    <div class="footer">
      <h3>Add position:</h3>
      <div class="row">
        <%= render position = @discussion.positions.new(user: @discussion.user) unless @discussion.published? %>
      </div>
      <hr>
      <%= render partial: "look_for_user"%>
      <%= render partial: "generate_token"%>
      <%= render partial: "publish", locals: {discussion: @discussion}%>
    </div>
  <%end%>

</div>