config/routes.rb
Rails.application.routes.draw do
  concern  :votable do
    member do #Create actually calls the CRUD method which figures out whether to Create, Update or Destroy the vote.
      get 'vote_up'
      get 'vote_down'
    end
  end
  
  concern :commentable do
    resources :comments, only: [:create, :index] do
      collection do
        get 'get_all'
      end
    end
  end
  
  resources :discussions, only: [:new, :create] do #Allowed creating new items only from logged user
  end
  
  resources :comments, concerns: [:votable, :commentable]
  
  resources :users do
    collection do
      get 'by_email'
    end
    resources :positions, only: [:index] do
    end
    resources :discussions, except: [:new, :create], shallow: true, concerns: [:votable, :commentable] do 
      member do
        get 'publish'
      end
      resources :positions, shallow: true, concerns: [:votable, :commentable] do
        collection do
          post 'new_token'
        end
      end
    end
  end
  
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  
  get 'signup' => 'users#new'
  
  delete 'logout' => 'sessions#destroy'
  
  get 'auth/:provider', to: redirect('/auth/%{provider}'), as: :social_login
  get 'auth/:provider/callback', to: 'sessions#oauthcreate'
  get 'auth/failure', to: redirect('/')
  
  get 'home' => 'home#stories'

  root 'sessions#redirect'

end

app/views/partials/_default_header.html.erb
<nav class="navbar navbar-default">
	<div class="container-fluid">
		<!-- Brand and toggle get grouped for better mobile display -->
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<%= link_to @config[:logo], root_path, class:"navbar-brand"%>
		</div>

		<!-- Collect the nav links, forms, and other content for toggling -->
		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			<ul class="nav navbar-nav">
				<li class="active">
					<%= link_to span("Random Debate ")+badge(@config[:discussions]), root_path %>
				</li>
				<li>
					<%= link_to span("Invitations ")+badge(@config[:invitations]), user_positions_path(@user)%>
				</li>
			</ul>
			<ul class="nav navbar-nav navbar-right">
				<li>
					<%= link_to span("",class:'glyphicon glyphicon-pencil')+" "+span("publish"), new_discussion_path, class:"btn btn-default"%>
				</li>
				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= @user.full_name%><span class="caret"></span></a>
					<ul class="dropdown-menu">
						<li>
							<%= link_to "Discussions", user_discussions_path(@user)%>
						</li>
						<li>
							<%= link_to "Profile", [:edit, @user]%>
						</li>
						<li role="separator" class="divider"></li>
						<li>
							<%= link_to "Log out", logout_path, method: :delete%>
						</li>
					</ul>
				</li>
			</ul>
		</div><!-- /.navbar-collapse -->
	</div><!-- /.container-fluid -->
</nav>

app/views/partials/_display_element_error.html.erb
<% if element&&element.errors.any? %>
<%element.errors.full_messages.each do |error|%>
<div class="alert <%= bootstrap_class_for("error") %> fade in">
	<button class="close" data-dismiss="alert">
		×
	</button>
	<%= error %>
</div>
<%end%>
<% end %>

app/views/partials/_display_errors.html.erb
<% flash.each do |type, message| %>
<div class="alert <%= bootstrap_class_for(type) %> fade in">
	<button class="close" data-dismiss="alert">
		×
	</button>
	<%= message %>
</div>
<% end %>

<%= list_errors @user%>
<%= list_errors @discussion%>
<%= list_errors @position%>

app/views/partials/_logged_out_header.html.erb
<nav class="navbar navbar-default">
	<div class="container-fluid">
		<!-- Brand and toggle get grouped for better mobile display -->
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<%= link_to @config[:logo], root_path, class:"navbar-brand"%>
		</div>

		<!-- Collect the nav links, forms, and other content for toggling -->
		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			<ul class="nav navbar-nav">
				<!--About-->
			</ul>
		</div><!-- /.navbar-collapse -->
	</div><!-- /.container-fluid -->
</nav>

app/views/partials/_look_for_user.html.erb
<div class="row">
	<div class="col-sm-4 col-md-4" id="search-box">
			<div class="thumbnail">
				<h3> <center>Look for user</center></h3>
				<div class="caption">
				  <%=form_for(:user, url:users_by_email_path, remote:true,format: :json, method: :get, html:{id:"search_form",'data-type' => 'json'}) do|f|%>
				  <%=f.email_field :email, placeholder:"E-mail",  class:"form-control" %>
				  <br>
				  <%=button_tag content_tag(:span, " Search", class:"glyphicon glyphicon-search"),  class:"form-control" %>
				  <%end%>
				 </div>
			</div>
	</div>
	<div class="col-sm-8 col-md-8" id="user-box">
			<div class="thumbnail">
				<h3> <center>User found!</center></h3>
				<div class="caption">
				  <p><b id="user_result_full_name"></b> was found using email <b id="user_result_email"></b></p>
				  <script>
				  	var route = "<%=@config[:look_for_user][:invite_link]%>"
				  </script>
				  <center><%=link_to 'Invite Him', "#", id: "invite_link", class:"btn btn-primary invite_link"%></center>
				 </div>
			</div>
	</div>
	<div class="col-sm-8 col-md-8" id="invite-box">
			<div class="thumbnail">
				<h3> <center>No user was found</center></h3>
				<div class="caption">
					<p>No user was found with e-mail: <b data-param="email"></b> </p>
					<center><%=link_to 'Invite Him', "#", id: "invite_link_2", class:"btn btn-primary invite_link", "data-param"=>"email"%></center>
				</div>
			</div>
	</div>
</div>

app/views/partials/_row.html.erb
<% extra_class ||= '' %>
<div class="row <%= extra_class %>">
  <%= render row %>
</div>