config/routes.rb
Rails.application.routes.draw do
  concern  :votable do
    member do #Create actually calls the CRUD method which figures out whether to Create, Update or Destroy the vote.
      get 'vote_up'
      get 'vote_down'
    end
  end
  
  concern :commentable do
    resources :comments, only: [:create, :index] do
      collection do
        get 'get_all'
      end
    end
  end
  
  resources :discussions, only: [:new, :create] do #Allowed creating new items only from logged user
  end
  
  resources :comments, concerns: [:votable, :commentable]
  
  resources :users do
    collection do
      get 'by_email'
    end
    resources :positions, only: [:index] do
    end
    resources :discussions, except: [:new, :create], shallow: true, concerns: [:votable, :commentable] do 
      member do
        get 'publish'
      end
      resources :positions, shallow: true, concerns: [:votable, :commentable] do
        collection do
          post 'new_token'
        end
      end
    end
  end
  
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  
  get 'signup' => 'users#new'
  
  delete 'logout' => 'sessions#destroy'
  
  get 'auth/:provider', to: redirect('/auth/%{provider}'), as: :social_login
  get 'auth/:provider/callback', to: 'sessions#oauthcreate'
  get 'auth/failure', to: redirect('/')
  
  get 'home' => 'home#stories'

  root 'sessions#redirect'

end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  before_save { self.email = email.downcase }
  validates :first_name, presence: true, length: {minimum: 2, maximum: 50}
  validates :last_name, presence: true, length: {minimum: 2, maximum: 50}
  validates :email, presence: true,
            uniqueness: {case_sensitive: false},
            format: {with: VALID_EMAIL_REGEX}
  validates :password, length: {minimum: 6}
  has_one :profile, class_name: "UserProfile"
  has_many :discussions
  has_many :positions, foreign_key: "email", primary_key: "email"

  def self.find_by_email(email)
    return User.find_by(email: email.downcase)
  end

  def self.from_omniauth(auth)
    if find_by(provider: auth.provider, uid: auth.uid) == find_by(email: auth.info.email)
      where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |user|
        user.provider = auth.provider
        user.uid = auth.uid
        user.first_name = auth.info.first_name
        user.last_name = auth.info.last_name
        user.oauth_token = auth.credentials.token
        user.oauth_expires_at = Time.at(auth.credentials.expires_at)
        user.email = auth.info.email
        user.password=(0...30).map { ('0'..'z').to_a[rand(75)] }.join
        user.save!
      end
    else
      false
    end
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  def owns?(object)
    self==object.try(:user) || self==object
  end

  def as_json(options={}) #Prevent key attributes to be sent in the JSON
    {
        :id => id,
        :first_name => first_name,
        :last_name => last_name,
        :full_name => full_name,
        :email => email
    }
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]
  before_action :only_admin, only: [:index, :destroy] #Only Administrators can list all users or destroy them
  before_action :get_user_or_redirect, only: [:show, :edit, :update, :by_email] #Only show the profiles to logged in users.
  before_action :config_email_disabled, only: [:edit, :update]
  before_action :user_match, only: [:edit, :update] # Only the user should have access to this content

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    show_user
  end
  
  def by_email
    @requested_user=User.find(User.find_by_email(params[:user][:email]).try(:id)) #Force 404 if user doesn't exist
    show_user
  end

  # GET /users/new
  def new  
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        format.html { log_in(@user,notice: "User was created successfully")}
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(modify_user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
  

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @requested_user = User.find(params[:id])
    end
    def show_user
      respond_to do |format|
        format.html {render 'show'}
        format.json {render json: @requested_user}
      end
    end
    
    def config_email_disabled
      @config[:email_disabled] = true
    end
    
    def user_match
      (@requested_user==@user)? true : redirect_to(root_path,{flash:{error:"Not enough permissions to do this"}})
      #TODO user the already created match from UserPermissions
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
    end
    
    def modify_user_params
      params.require(:user).permit(:first_name, :last_name, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
  def link_to_user(user = @user, options = {})
    options[:class]||="user_link"
    link_to(user.full_name, user, options)
  end
  
  def owns?(object)
    @user.owns?(object)
  end
  
  def editable?(object)
    !!object.try(:editable?,@user)
  end
end

app/views/users/_discussion.html.erb
<% discussion=position.discussion%>
<div class="col-sm-6 col-md-4">
	<div class="thumbnail">
		<div class="caption">
			<h3> <%= discussion.header%></h3>
			<p>
				<b>Type:</b> <%= discussion.type.name%>
			</p>
			<p>
				<b>Topic:</b> <%= discussion.topic.name%>
			</p>
			<p>
				<%= simple_format(discussion.body)%>
			</p>
		</div>
		<div class="caption footer">
			<p>
				<%= link_to "View", discussion, class:"btn btn-primary", style:"width:100%"%>
				<hr>
				<%= link_to "Accept", edit_position_path(position), class:"btn btn-success"%> |
				<%= link_to "Reject", position, class:"btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' }%>
				<br>
				<hr>
				<span>Invited by:</span> <%= link_to discussion.user.full_name, discussion.user%>
			</p>
		</div>
	</div>
</div>

app/views/users/_form.html.erb
<%= form_for @user, class:"form-signin" do |f| %> <h1><%= @config[:h1]%></h1>

<%= f.label :email %>
<%= f.text_field :email,  class:"form-control", disabled:@config[:email_disabled] %>

<%= f.label :first_name %>
<%= f.text_field :first_name,  class:"form-control" %>

<%= f.label :last_name %>
<%= f.text_field :last_name,  class:"form-control" %>

<%= f.label :password, "Password:" %>
<%= f.password_field :password,  class:"form-control"  %>

<%= f.label :password_confirmation, "Password Confirmation:" %>
<%= f.password_field :password_confirmation,  class:"form-control"  %>
<br>
<%= f.submit class:"btn btn-primary"%>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

app/views/users/new.html.erb
<% @config[:h1]="Sign Up"%>

<%= render 'form' %>

app/views/users/show.html.erb
<p>
	<strong>First name:</strong>
	<%= @requested_user.first_name %>
</p>

<p>
	<strong>Last name:</strong>
	<%= @requested_user.last_name %>
</p>

<%= link_to "Discussions", [@requested_user, Discussion] %>
<br>
<%= #link_to "Positions", [@requested_user, Position]
%>